name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:run

      - name: Merge mochawesome JSONs
        run: npm run report:merge

      - name: Generate Mochawesome HTML report
        run: npm run report:open

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Cypress Test Report"
          to: "ahmed.asho@yahoo.com"
          from: "Cypress Bot <${{ secrets.SMTP_USERNAME }}>"
          body: "Hello Ahmed, please find the Cypress test report attached."
          attachments: mochawesome-report/mochawesome.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
